# NUMPY ASSIGNMENT 

1. Create a 1D array of numbers from 0 to 9

In [1]:
import numpy as np
x = np.arange(9)
print("1D array of numbers from 0 to 9 :")
print(x)

1D array of numbers from 0 to 9 :
[0 1 2 3 4 5 6 7 8]


2. Create a 3×3 numpy array of all True’s

In [2]:
x = np.ones((3,3), dtype=bool)
 
print('3x3 array of all True: \n')
print(x,x.shape,'\n\n')  

3x3 array of all True: 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] (3, 3) 




3. Given an array as input, print only odd numbers as output

In [3]:
arr1 = [45,90,55,23,21,78,10]

for i in arr1:
    if i % 2 != 0:
        print(i)

45
55
23
21


4. Replace all odd numbers in arr with -2

In [4]:
arr1 = [45,91,55,24,11,78,10]
i = 0

while(i < len(arr1)):
    if arr1[i] % 2 != 0:
        arr1[i] = -2
    i +=1
print(arr1)

[-2, -2, -2, 24, -2, 78, 10]


    5. How to reshape an array?

In [5]:
#create an array with (2,3)
list1 = np.arange(6).reshape(2,3)
list1

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
np.reshape(list1,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

    6. Convert a 1D array to a 2D array with 2 rows

In [7]:
a= np.arange(1,9)
print('Original array shape:\t',a.shape)

a_2d = a.reshape(2,4)
print('Modified 2D array shape:\t',a_2d.shape)
print('2D array elements:\n',a_2d)

Original array shape:	 (8,)
Modified 2D array shape:	 (2, 4)
2D array elements:
 [[1 2 3 4]
 [5 6 7 8]]


    7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [8]:
a  = [1,2,3,4,5,6,7,8,9]

for i in a:
    if ((i % 2 != 0) & (i % 4 ==0)):
        b = i
        print(b)

print("There is no odd number & 4 multiples combination in b")
        

There is no odd number & 4 multiples combination in b


    8. Given array, check if there are any null values and print them out. 

In [29]:
#Create array of numbers
x = np.array(range(10,30,2))

x = np.append(x,np.nan)     # Added null value as the initial array doesnt have null values
x

#Check if there are any null values
x[np.isnan(x)]

array([nan])

    9. How to replace all missing values with 0 in a numpy array?

In [31]:
x[np.isnan(x)] = 0
x

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.,  0.])

    10. How to find the count of each unique number in a NumPy array?

In [33]:
#create array 
arr = np.array([9,2,1,5,45,16,12,89,78,1,3,2])

print("Original array:\t",arr)

#Unique values
print("Unique values:\t",np.unique(arr))

Original array:	 [ 9  2  1  5 45 16 12 89 78  1  3  2]
Unique values:	 [ 1  2  3  5  9 12 16 45 78 89]


    11. How to convert a numeric to a categorical (text) array?

In [37]:
#Create numeric array
arr_num = np.arange(5)

# numpy.array2string(a, max_line_width=None, precision=None, suppress_small=None, separator=' ', prefix='', 
#style=<no value>, formatter=None, threshold=None, edgeitems=None, sign=None, floatmode=None, suffix='', **kwarg)

#np.array2string(arr_num,  

    12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

In [21]:
ser = np.arange(99,299)
i = 0

while i < len(ser):
    if (ser[i] % 7 == 0) & (ser[i] % 5 == 0):
        pass
    elif (ser[i] % 7 ==0) or (ser[i] % 5 == 0):
        print(ser[i])
    i += 1         


100
110
112
115
119
120
125
126
130
133
135
145
147
150
154
155
160
161
165
168
170
180
182
185
189
190
195
196
200
203
205
215
217
220
224
225
230
231
235
238
240
250
252
255
259
260
265
266
270
273
275
285
287
290
294
295


    13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [ ]:
a  = [1,2,3,4,5,6,7,8,9]

print("Original Array:",a)

a1 = a[::-1]
print("reversed array:",a1)